server:
  port: 80
spring:
  mvc:
    servlet:
      load-on-startup: 1
  datasource:
    url:
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: org.jplus.web.mapper
