server:
  port: 80
spring:
  mvc:
    servlet:
      load-on-startup: 1
  datasource:
    url: jdbc:mysql://10.30.170.43:3306/jxgldb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      maxActive: 500
      maxWait: 10000
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: org.jplus.web.mapper